// auto generated by go tool dist

package cfg

const DefaultCC = `/home/nopparat/host/bin/arm-buildroot-linux-gnueabihf-gcc`
const DefaultCXX = `/home/nopparat/host/bin/arm-buildroot-linux-gnueabihf-g++`
const DefaultPkgConfig = `pkg-config`
