// auto generated by go tool dist

package main

const defaultCC = `/home/nopparat/host/bin/arm-buildroot-linux-gnueabihf-gcc`
const defaultCXX = `/home/nopparat/host/bin/arm-buildroot-linux-gnueabihf-g++`
const defaultPkgConfig = `pkg-config`
