QT.gui_private.VERSION = 5.14.2
QT.gui_private.name = QtGui
QT.gui_private.module =
QT.gui_private.libs = $$QT_MODULE_LIB_BASE
QT.gui_private.includes = $$QT_MODULE_INCLUDE_BASE/QtGui/5.14.2 $$QT_MODULE_INCLUDE_BASE/QtGui/5.14.2/QtGui
QT.gui_private.frameworks =
QT.gui_private.depends = core_private gui
QT.gui_private.uses =
QT.gui_private.module_config = v2 internal_module
QT.gui_private.enabled_features = drm_atomic egl eglfs kms eglfs_egldevice eglfs_gbm evdev freetype system-freetype fontconfig gif ico jpeg libinput libinput-axis-api linuxfb mtdev multiprocess png raster-64bit system-jpeg system-png tuiotouch vkgen vnc xkbcommon
QT.gui_private.disabled_features = xcb accessibility-atspi-bridge dxguid angle_d3d11_qdtd direct2d direct2d1_1 dxgi direct3d11 direct3d11_1 direct3d9 directfb dxgi1_2 egl_x11 eglfs_brcm eglfs_mali eglfs_openwfd eglfs_rcar eglfs_viv eglfs_viv_wl vsp2 eglfs_vsp2 xlib xcb-xlib eglfs_x11 harfbuzz integrityfb integrityhid system-harfbuzz system-xcb tslib
QMAKE_INCDIR_OPENGL_ES2 = 
QMAKE_INCDIR_DRM = /home/nopparat/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/libdrm
QMAKE_DEFINES_EGL = MESA_EGL_NO_X11_HEADERS
QMAKE_INCDIR_EGL = 
QMAKE_DEPENDS_FREETYPE_CC = ZLIB
QMAKE_DEPENDS_FREETYPE_LD = ZLIB
QMAKE_INCDIR_FREETYPE = /home/nopparat/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/freetype2
QMAKE_DEPENDS_FONTCONFIG_CC = FREETYPE
QMAKE_DEPENDS_FONTCONFIG_LD = FREETYPE
QMAKE_INCDIR_FONTCONFIG = /home/nopparat/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/uuid
QMAKE_DEPENDS_LIBPNG_CC = ZLIB
QMAKE_DEPENDS_LIBPNG_LD = ZLIB
QMAKE_INCDIR_LIBPNG = /home/nopparat/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/libpng16
QMAKE_LIBS_OPENGL_ES2 = -L/home/nopparat/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib -lmali -lGLESv2
QMAKE_LIBS_DRM = -L/home/nopparat/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib -ldrm
QMAKE_LIBS_EGL = -L/home/nopparat/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib -lmali -lEGL
QMAKE_LIBS_GBM = -L/home/nopparat/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib -lmali -lgbm
QMAKE_LIBS_FREETYPE = -L/home/nopparat/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib -lfreetype
QMAKE_LIBS_FONTCONFIG = -lfontconfig
QMAKE_LIBS_LIBINPUT = -L/home/nopparat/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib -linput
QMAKE_LIBS_MTDEV = -L/home/nopparat/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib -lmtdev
QMAKE_LIBS_LIBJPEG = -L/home/nopparat/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib -ljpeg
QMAKE_LIBS_LIBPNG = -L/home/nopparat/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib -lpng16
QMAKE_LIBS_XKBCOMMON = -L/home/nopparat/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib -lxkbcommon
